"use client";

import { useEffect, useRef, useState } from "react";
import { Loader2 } from "lucide-react";

import { Input } from "@/components/ui/input";

// Runtime-only module generated by the postbuild Pagefind step
// (public/pagefind/pagefind.js) -- it doesn't exist on disk for TypeScript
// to resolve, only served at this URL after `pnpm build` has run. Routed
// through a variable (rather than a literal in the import() call) so
// TypeScript doesn't try to statically resolve the path -- a leading `/`
// is treated as a real filesystem path, not a bare specifier, so a
// `declare module "/pagefind/pagefind.js"` ambient declaration never gets
// consulted for it.
const PAGEFIND_MODULE_PATH: string = "/pagefind/pagefind.js";

type PagefindResultData = {
  url: string;
  excerpt: string;
  meta: { title?: string };
};

type PagefindModule = {
  search: (
    query: string,
    options?: { filters?: Record<string, string | string[]> },
  ) => Promise<{
    results: { id: string; data: () => Promise<PagefindResultData> }[];
  }>;
};

type Status = "loading-index" | "ready" | "unavailable";

/**
 * Pagefind derives result URLs from the indexed file's path under
 * `.next/server/app` (e.g. `/javascript/closures.html`), which doesn't
 * match the clean route Next actually serves (`/javascript/closures`).
 * Pagefind only auto-strips a trailing `index.html`, not arbitrary
 * `<slug>.html` files, so this app has to do it.
 */
function toRoutePath(pagefindUrl: string): string {
  return pagefindUrl.replace(/(?:\/index)?\.html$/, "") || "/";
}

export function SearchBox() {
  const [query, setQuery] = useState("");
  const [results, setResults] = useState<PagefindResultData[]>([]);
  const [status, setStatus] = useState<Status>("loading-index");
  const [isSearching, setIsSearching] = useState(false);
  const pagefindRef = useRef<PagefindModule | null>(null);

  useEffect(() => {
    let cancelled = false;

    async function loadPagefind() {
      try {
        const mod = (await import(
          /* webpackIgnore: true */ PAGEFIND_MODULE_PATH
        )) as PagefindModule;
        if (cancelled) return;
        pagefindRef.current = mod;
        setStatus("ready");
      } catch {
        if (!cancelled) setStatus("unavailable");
      }
    }

    loadPagefind();
    return () => {
      cancelled = true;
    };
  }, []);

  useEffect(() => {
    if (status !== "ready" || query.trim() === "") {
      setResults([]);
      setIsSearching(false);
      return;
    }

    let cancelled = false;
    setIsSearching(true);

    async function runSearch() {
      const search = await pagefindRef.current!.search(query);
      const data = await Promise.all(
        search.results.map((result) => result.data()),
      );
      if (!cancelled) {
        setResults(data);
        setIsSearching(false);
      }
    }

    runSearch();
    return () => {
      cancelled = true;
    };
  }, [query, status]);

  const showSpinner = status === "loading-index" || isSearching;

  return (
    <div>
      <div className="relative">
        <Input
          type="search"
          value={query}
          onChange={(event) => setQuery(event.target.value)}
          placeholder="Search lessons…"
          disabled={status === "unavailable"}
          aria-label="Search lessons"
          className={showSpinner ? "pr-8" : undefined}
        />
        {showSpinner && (
          <Loader2
            className="absolute top-1/2 right-2.5 size-4 -translate-y-1/2 animate-spin text-muted-foreground"
            aria-hidden
          />
        )}
      </div>

      {status === "loading-index" && (
        <p className="text-muted-foreground mt-4 text-sm">
          Loading search index…
        </p>
      )}

      {status === "unavailable" && (
        <p className="text-muted-foreground mt-4 text-sm">
          Search isn&apos;t available in this environment -- the index is only
          built as part of <code>pnpm build</code>, not <code>pnpm dev</code>.
        </p>
      )}

      {status === "ready" && query.trim() !== "" && (
        <ul className="mt-6 space-y-6">
          {results.length === 0 ? (
            <li className="text-muted-foreground text-sm">
              No lessons match &quot;{query}&quot;.
            </li>
          ) : (
            results.map((result) => (
              <li key={result.url}>
                <a
                  href={toRoutePath(result.url)}
                  className="text-lg font-medium hover:underline"
                >
                  {result.meta.title ?? result.url}
                </a>
                <p
                  className="text-muted-foreground mt-1 text-sm [&_mark]:bg-primary/20 [&_mark]:text-foreground [&_mark]:rounded-sm"
                  dangerouslySetInnerHTML={{ __html: result.excerpt }}
                />
              </li>
            ))
          )}
        </ul>
      )}
    </div>
  );
}
